### ISSUE TITLE
Unable to run the basic compile from Jenkins installed in windows for this 'jgsu-spring-petclinic' code

### ISSUE THREAD

**Issue by Navanee-kannan** [g0t4/jgsu-spring-petclinic#3]
Unable to run the basic compile from Jenkins installed in windows for this 'jgsu-spring-petclinic' code

1.  I was able to get the repository from Jenkins and branches are correct as 'main'
2. Builld was successful and the code was pulled in my local
3. Next step, tried compiling from Jenkins (./mvnw compile ) in 'Execute shell' , it throws below error

**Note**: 
1. if I run manually in windows command prompt for the same code, the compilation works (mvnw.cmd compile)
2. I also tried to run 'mvnw.cmd compile' from Jenkins still failed with below error.

Any suggestions?

**console error**
---------------------
Started by user Navaneetha kannan
Running as SYSTEM
Building in workspace C:\Users\nvenkate\.jenkins\workspace\spring-petclinic
The recommended git tool is: NONE
No credentials specified
 > git.exe rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git.exe config remote.origin.url https://github.com/g0t4/jgsu-spring-petclinic.git # timeout=10
Fetching upstream changes from https://github.com/g0t4/jgsu-spring-petclinic.git
 > git.exe --version # timeout=10
 > git --version # 'git version 2.30.0.windows.1'
 > git.exe fetch --tags --force --progress -- https://github.com/g0t4/jgsu-spring-petclinic.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git.exe rev-parse "refs/remotes/origin/main^{commit}" # timeout=10
Checking out Revision d18f22a419c770767748385bfc08e8be3177b003 (refs/remotes/origin/main)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f d18f22a419c770767748385bfc08e8be3177b003 # timeout=10
Commit message: "Revert "break a test""
 > git.exe rev-list --no-walk d18f22a419c770767748385bfc08e8be3177b003 # timeout=10
[spring-petclinic] $ sh -xe C:\Users\nvenkate\AppData\Local\Temp\jenkins17760341579666375071.sh
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
Caused: java.io.IOException: Cannot run program "sh" (in directory "C:\Users\nvenkate\.jenkins\workspace\spring-petclinic"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:996)
	at hudson.Launcher$ProcStarter.start(Launcher.java:508)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:143)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:91)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
	at hudson.model.Build$BuildExecution.build(Build.java:197)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:513)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by Navanee-kannan** [comment]
this is invalid issue - for windows, we need to use batch run instead of shell run.
Apologies for the invalid defect

**Comment by g0t4** [comment]
I appreciate you bringing this up! I had a bit about this in my first course. Would a mention in the course be helpful? I can't recall if that made it into the 2nd or just 1st edition of the course.

**Comment by g0t4** [comment]
Thanks for sharing your solution so others can benefit too!

**Comment by g0t4** [comment]
And yes that won't be obvious from the long stack trace! 

> The system cannot find the file specified

Super helpful message! (not intended to impugn anyone that wrote that code, just an observation, I've written my fair share of super helpful error messages in my life ;) )
